apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadvisor
resources:
- daemonset.yaml
- namespace.yaml
- serviceaccount.yaml
labels:
- includeSelectors: true
  pairs:
    app: cadvisor
