apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadvisor
commonLabels:
  app: cadvisor
resources:
- cluserrole.yaml
- cluserrolebinding.yaml
- daemonset.yaml
- namespace.yaml
- podsecuritypolicy.yaml
- serviceaccount.yaml
